name: Meals
permission:
  default: 0
folder: ''
flags: {}
content: |-
  <ul>
  <li>A hearty meal for one&nbsp; 1 coin</li>
  <li>A poor meal for a family&nbsp; 1 coin</li>
  <li>A feast&nbsp; 15 coins per person</li>
  </ul>
_id: wqTidtrlYe7XXraO
