name: Services
permission:
  default: 0
folder: ''
flags: {}
content: |-
  <ul>
  <li>A week’s stay at a peasant inn&nbsp; 14-Charisma coins</li>
  <li>A week’s stay at a civilized inn&nbsp; 30-Charisma coins</li>
  <li>A week’s stay at the fanciest inn in town&nbsp; 43-Charisma coins</li>
  <li>A week’s unskilled mundane labor&nbsp; 10 coins</li>
  <li>A month’s pay for enlistment in an army&nbsp; 30 coins</li>
  <li>A custom item from a blacksmith&nbsp; Base Item + 50 coins</li>
  <li>A night’s “companionship”&nbsp; 20-Charisma coins</li>
  <li>An evening of song and dance&nbsp; 18-Charisma coins</li>
  <li>Escort for a day along a bandit-infested road&nbsp; 20 coins</li>
  <li>Escort for a day along a monster-infested road&nbsp; 54 coins</li>
  <li>A run-of-the-mill killing&nbsp; 5 coins</li>
  <li>An assassination&nbsp; 120 coins</li>
  <li>Healing from a chirurgeon&nbsp; 5 coins</li>
  <li>A month’s prayers for the departed&nbsp; 1 coin</li>
  <li>Repairs to a mundane item&nbsp; 25% of the item’s cost</li>
  </ul>
